# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 527)
        MainWindow.setStyleSheet("padding:0")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 361))
        self.groupBox.setStyleSheet("border:3px solid black")
        self.groupBox.setObjectName("groupBox")
        self.label_show = QtWidgets.QLabel(self.groupBox)
        self.label_show.setGeometry(QtCore.QRect(20, 19, 471, 321))
        self.label_show.setStyleSheet("border:0px solid red")
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 10, 281, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 131, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 121, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.stackedWidget_Recycle = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget_Recycle.setGeometry(QtCore.QRect(10, 70, 110, 110))
        self.stackedWidget_Recycle.setStyleSheet("")
        self.stackedWidget_Recycle.setObjectName("stackedWidget_Recycle")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_Recycle.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_Recycle.addWidget(self.page_2)
        self.stackedWidget_Kitchen = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget_Kitchen.setGeometry(QtCore.QRect(140, 70, 110, 110))
        self.stackedWidget_Kitchen.setStyleSheet("")
        self.stackedWidget_Kitchen.setObjectName("stackedWidget_Kitchen")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_Kitchen.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_Kitchen.addWidget(self.page_4)
        self.stackedWidget_Harmful = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget_Harmful.setGeometry(QtCore.QRect(10, 220, 110, 110))
        self.stackedWidget_Harmful.setStyleSheet("")
        self.stackedWidget_Harmful.setObjectName("stackedWidget_Harmful")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_Harmful.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget_Harmful.addWidget(self.page_6)
        self.stackedWidget_Other = QtWidgets.QStackedWidget(self.groupBox_2)
        self.stackedWidget_Other.setGeometry(QtCore.QRect(140, 220, 110, 110))
        self.stackedWidget_Other.setStyleSheet("")
        self.stackedWidget_Other.setObjectName("stackedWidget_Other")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget_Other.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_Other.addWidget(self.page_8)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(170, 190, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 340, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(170, 340, 72, 15))
        self.label_7.setObjectName("label_7")
        self.textEdit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 400, 411, 121))
        self.textEdit_log.setReadOnly(True)
        self.textEdit_log.setObjectName("textEdit_log")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 380, 171, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 380, 351, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(490, 380, 331, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_recycle = QtWidgets.QLabel(self.centralwidget)
        self.label_recycle.setGeometry(QtCore.QRect(450, 440, 81, 16))
        self.label_recycle.setObjectName("label_recycle")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 490, 72, 15))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(630, 490, 72, 15))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(620, 440, 91, 16))
        self.label_12.setObjectName("label_12")
        self.label_recyle = QtWidgets.QLabel(self.centralwidget)
        self.label_recyle.setGeometry(QtCore.QRect(540, 440, 72, 15))
        self.label_recyle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_recyle.setObjectName("label_recyle")
        self.label_kitchen = QtWidgets.QLabel(self.centralwidget)
        self.label_kitchen.setGeometry(QtCore.QRect(540, 490, 72, 15))
        self.label_kitchen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kitchen.setObjectName("label_kitchen")
        self.label_other = QtWidgets.QLabel(self.centralwidget)
        self.label_other.setGeometry(QtCore.QRect(730, 490, 72, 15))
        self.label_other.setAlignment(QtCore.Qt.AlignCenter)
        self.label_other.setObjectName("label_other")
        self.label_harmful = QtWidgets.QLabel(self.centralwidget)
        self.label_harmful.setGeometry(QtCore.QRect(730, 440, 72, 15))
        self.label_harmful.setAlignment(QtCore.Qt.AlignCenter)
        self.label_harmful.setObjectName("label_harmful")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(430, 400, 72, 15))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_Kitchen.setCurrentIndex(0)
        self.stackedWidget_Harmful.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "视频显示区"))
        self.groupBox_2.setTitle(_translate("MainWindow", "状态信息"))
        self.label.setText(_translate("MainWindow", "主  机  状  态:"))
        self.label_2.setText(_translate("MainWindow", "待机中"))
        self.label_3.setText(_translate("MainWindow", "垃圾桶已用容量:"))
        self.label_4.setText(_translate("MainWindow", "可回收垃圾"))
        self.label_5.setText(_translate("MainWindow", "厨余垃圾"))
        self.label_6.setText(_translate("MainWindow", "有害垃圾"))
        self.label_7.setText(_translate("MainWindow", "其他垃圾"))
        self.label_8.setText(_translate("MainWindow", "识别结果及提示"))
        self.label_recycle.setText(_translate("MainWindow", "可回收垃圾"))
        self.label_10.setText(_translate("MainWindow", "厨余垃圾"))
        self.label_11.setText(_translate("MainWindow", "其他垃圾"))
        self.label_12.setText(_translate("MainWindow", "有害垃圾"))
        self.label_recyle.setText(_translate("MainWindow", "0"))
        self.label_kitchen.setText(_translate("MainWindow", "0"))
        self.label_other.setText(_translate("MainWindow", "0"))
        self.label_harmful.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "投入数量:"))
